### ISSUE TITLE
Better `.cacheKey` serialization

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/mem#38] opened 2019-05-18 08:43 UTC
Following the https://github.com/sindresorhus/mem/pull/35 conversation, I saw the point is it can't serialize functions.

Following the https://github.com/sindresorhus/mem/pull/35 conversation, I saw the point is it can't serialize functions.
Thinking into if you need to use a custom `cacheKey` or not based on the type of your arguments is a bit tedious. Something in an automatic way is very welcome here

Maybe not `JSON.stringify`, but [serialize-javascript](https://github.com/yahoo/serialize-javascript), a superset of JSON can do that (also for regex). It has been designed for that.

Jus we can leverage the functionality replacing the current `cacheKey` for something like

```js
const serialize = require('serialize-javascript')
const cacheKey = (...args) => args.reduce((acc, arg) => `${acc}:${serialize(arg)}`, '')
```

or maybe just

```js
const serialize = require('serialize-javascript')
const cacheKey = (...args) => serialize(args)
````

Thoughts?

**Comment by bfred-it** [comment] 2019-05-18 12:41
That’s what I’m hoping to find, however does it also support Symbols?

We need a fast one-way serializer/hasher with wide support.

**Comment by Kikobeats** [comment] 2019-05-18 14:17
Looks like `serialize-javascript` doesn't support symbol [yet](https://github.com/yahoo/serialize-javascript/issues/13) but could be possible do that.

I suppose the faster solution should be using [v8.serialize](https://nodejs.org/api/v8.html#v8_v8_serialize_value) but not sure about function/symbol support there

**Comment by bfred-it** [comment] 2019-05-18 14:18
`mem` has to keep working in the browser too

**Comment by bfred-it** [comment] 2019-05-18 14:22
I think we can't rely on `function#toString()` to deduplicate functions because `function () {return this}` and `function () {return this}` look identical but they can be bound to different objects. Functions and Symbols have to be remembered by reference.

**Comment by bfred-it** [comment] 2019-05-26 05:42
Closing this as the issue is the same as #20. Conversation can continue there or in #22

**Closed by bfred-it** 2019-05-26 05:42 UTC
